migrating to melodic
ros-industrial-attic/fermi pull request #48
Opened 2019-01-14 16:44 UTC by ahcorde

2019-01-15 19:31 UTC, jrgnicho requested changes
@ahcorde  thanks for submitting this.  Could you please address the comments;  I'll test this on a melodic system soon.

2019-01-15 19:31 UTC, jrgnicho commented on moveit_cartesian_plan_plugin/CMakeLists.txt
> +add_definitions(-std=c++11)
This is redundant as there already is a -std=c++11 compile option at the top of the file

2019-01-15 19:31 UTC, jrgnicho commented on moveit_cartesian_plan_plugin/CMakeLists.txt
> +  moveit_ros_warehouse
Are the warehouse or perception libraries necessary?

2019-01-15 19:31 UTC, jrgnicho commented on moveit_cartesian_plan_plugin/CMakeLists.txt
> +# add_definitions(-DQT_NO_KEYWORDS)
Remove commented commands

2019-01-15 19:31 UTC, jrgnicho commented on moveit_cartesian_plan_plugin/CMakeLists.txt
> +# qt_wrap_ui(moveit_cartesian_plan_plugin_UIS_H ${moveit_cartesian_plan_plugin_UIS})
remove commented commands

2019-01-15 19:31 UTC, jrgnicho commented on moveit_cartesian_plan_plugin/CMakeLists.txt
> +if(rviz_QT_VERSION VERSION_LESS "5")
This qt library resolution is already done above

2019-01-15 19:31 UTC, jrgnicho commented on moveit_cartesian_plan_plugin/CMakeLists.txt
> +  # ${QT_QTGUI_LIBRARY}
Remove commented commands

2019-01-15 19:31 UTC, jrgnicho commented on moveit_cartesian_plan_plugin/include/moveit_cartesian_plan_plugin/add_way_point.hpp
> +// #include <QtConcurrentRun>
Remove commented code

2019-01-15 19:31 UTC, jrgnicho commented on moveit_cartesian_plan_plugin/include/moveit_cartesian_plan_plugin/generate_cartesian_path.hpp
> +// #include <moveit/planning_interface/planning_interface.h>
Same as above

2019-01-15 19:31 UTC, jrgnicho commented on moveit_cartesian_plan_plugin/include/moveit_cartesian_plan_plugin/generate_cartesian_path.hpp
> +// #include <QtConcurrentRun>
Same as above

2019-01-15 19:31 UTC, jrgnicho commented on moveit_cartesian_plan_plugin/include/moveit_cartesian_plan_plugin/generate_cartesian_path.hpp
> +//#include <moveit/move_group_interface/move_group.h>
Why change the extension of the file to **hpp**?

2019-01-15 19:31 UTC, jrgnicho commented on moveit_cartesian_plan_plugin/include/moveit_cartesian_plan_plugin/generate_cartesian_path.hpp
> +namespace move_group_interface = moveit::planning_interface;
this namespace isn't being used

2019-01-15 19:31 UTC, jrgnicho commented on moveit_cartesian_plan_plugin/include/moveit_cartesian_plan_plugin/widgets/path_planning_widget.hpp
> +// #include <QtConcurrentRun>
Remove commented code

2019-01-15 19:31 UTC, jrgnicho commented on moveit_cartesian_plan_plugin/plugin.xml
>    </class>
Did this plugin get deleted?

2019-01-15 19:31 UTC, jrgnicho commented on moveit_cartesian_plan_plugin/src/generate_cartesian_path.cpp
> +#include <moveit_cartesian_plan_plugin/generate_cartesian_path.hpp>
What functionality does this header bring in that wasn't here before?

2019-01-15 19:31 UTC, jrgnicho commented on moveit_cartesian_plan_plugin/src/point_tree_model.cpp
> +#include <moveit_cartesian_plan_plugin/point_tree_model.hpp>
Why change the extension to **hpp**?

2019-01-21 08:50 UTC, ahcorde commented
reviewed it

2019-04-05 10:44 UTC, rkojcev commented
addressed some of the @jrgnicho comments and opened a new PR in https://github.com/ros-industrial-consortium/fermi/pull/50. Thanks @ahcorde for helping.

2019-04-05 10:44 UTC, closed without merging